id: user.tmgmt_translation_skills
uuid: 28b5356d-7d95-4a0d-ab1f-38d8bb2d3b63
status: true
langcode: en
name: tmgmt_translation_skills
entity_type: user
type: tmgmt_language_combination
settings: {  }
module: tmgmt_language_combination
active: true
locked: false
cardinality: '-1'
translatable: false
indexes: {  }
