base_field: tjiid
base_table: tmgmt_job_item
core: 8.x
description: ''
status: '1'
display:
  block:
    display_plugin: block
    id: block
    display_title: Block
    position: '1'
    display_options: {  }
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: '1'
    display_options:
      access:
        type: none
        options: {  }
      cache:
        type: none
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: '0'
          distinct: '0'
          slave: '0'
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: '0'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: '1'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: full
        options:
          items_per_page: '10'
          offset: '0'
          id: '0'
          total_pages: ''
          expose:
            items_per_page: '0'
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: '0'
            items_per_page_options_all_label: '- All -'
            offset: '0'
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          quantity: '9'
      style:
        type: table
      row:
        type: fields
      fields:
        label:
          id: label
          table: tmgmt_job_item
          field: label
          relationship: none
          group_type: group
          admin_label: ''
          label: Label
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          link_to_entity: '0'
          plugin_id: entity_label
          provider: views
        type:
          id: type
          table: tmgmt_job_item
          field: type
          exclude: ''
        state:
          id: state
          table: tmgmt_job_item
          field: state
          relationship: none
          group_type: group
          admin_label: ''
          label: State
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          machine_name: '0'
          plugin_id: machine_name
          provider: views
        progress:
          id: progress
          table: tmgmt_job_item
          field: progress
          relationship: none
          group_type: group
          admin_label: ''
          label: Progress
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          plugin_id: tmgmt_progress
          provider: tmgmt
        word_count:
          id: word_count
          table: tmgmt_job_item
          field: word_count
          relationship: none
          group_type: group
          admin_label: ''
          label: 'Word count'
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          set_precision: '0'
          precision: '0'
          decimal: .
          separator: ','
          format_plural: '0'
          format_plural_singular: '1'
          format_plural_plural: '@count'
          prefix: ''
          suffix: ''
          plugin_id: numeric
          provider: views
        changed:
          id: changed
          table: tmgmt_job_item
          field: changed
          relationship: none
          group_type: group
          admin_label: ''
          label: Changed
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          date_format: short
          custom_date_format: ''
          timezone: ''
          plugin_id: date
          provider: views
        operations:
          id: operations
          table: tmgmt_job_item
          field: operations
          plugin_id: tmgmt_handler_field_tmgmt_job_item_operations
          exclude: ''
      filters: {  }
      sorts: {  }
      title: 'Job Items'
      header: {  }
      footer: {  }
      empty:
        area:
          id: area
          table: views
          field: area
          relationship: none
          group_type: group
          admin_label: ''
          empty: '1'
          tokenize: '0'
          content: 'There are no items attached to this translation job.'
          format: basic_html
          plugin_id: text
          provider: views
      relationships: {  }
      arguments:
        tjid:
          id: tjid
          table: tmgmt_job_item
          field: tjid
          relationship: none
          group_type: group
          admin_label: ''
          default_action: ignore
          exception:
            value: all
            title_enable: '0'
            title: All
          title_enable: '0'
          title: ''
          breadcrumb_enable: '0'
          breadcrumb: ''
          default_argument_type: fixed
          default_argument_options:
            argument: ''
          default_argument_skip_url: '0'
          summary_options:
            base_path: ''
            count: '1'
            items_per_page: '25'
            override: '0'
          summary:
            sort_order: asc
            number_of_records: '0'
            format: default_summary
          specify_validation: '0'
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          break_phrase: '0'
          not: '0'
          plugin_id: numeric
          provider: views
  submit:
    display_plugin: block
    id: submit
    display_title: 'Submit list'
    position: '2'
    display_options:
      display_description: ''
      fields:
        label:
          id: label
          table: tmgmt_job_item
          field: label
          relationship: none
          group_type: group
          admin_label: ''
          label: Label
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          link_to_entity: '0'
          plugin_id: entity_label
          provider: views
        type:
          id: type
          table: tmgmt_job_item
          field: type
          exclude: ''
        word_count:
          id: word_count
          table: tmgmt_job_item
          field: word_count
          relationship: none
          group_type: group
          admin_label: ''
          label: 'Word count'
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          set_precision: '0'
          precision: '0'
          decimal: .
          separator: ','
          format_plural: '0'
          format_plural_singular: '1'
          format_plural_plural: '@count'
          prefix: ''
          suffix: ''
          plugin_id: numeric
          provider: views
        operations:
          id: operations
          table: tmgmt_job_item
          field: operations
          plugin_id: tmgmt_handler_field_tmgmt_job_item_operations
          exclude: ''
      defaults:
        fields: '0'
    new_id: submit
label: 'Translation Job Items'
module: views
id: tmgmt_ui_job_items
tag: ''
uuid: 063e60dd-1a31-47e5-b628-483d7c00a2f2
langcode: en
