base_field: mid
base_table: tmgmt_message
core: 8.x
description: ''
status: '1'
display:
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: '1'
    display_options:
      access:
        type: none
        options: {  }
      cache:
        type: none
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: '0'
          distinct: '0'
          slave: '0'
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: '0'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: '1'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: full
        options:
          items_per_page: '10'
          offset: '0'
          id: '0'
          total_pages: ''
          expose:
            items_per_page: '0'
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: '0'
            items_per_page_options_all_label: '- All -'
            offset: '0'
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          quantity: '9'
      style:
        type: table
      row:
        type: fields
      fields:
        created:
          id: created
          table: tmgmt_message
          field: created
          relationship: none
          group_type: group
          admin_label: ''
          label: Created
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          date_format: html_date
          custom_date_format: ''
          timezone: ''
          plugin_id: date
          provider: views
        message:
          id: message
          table: tmgmt_message
          field: message
          plugin_id: tmgmt_handler_field_tmgmt_message_message
          exclude: ''
        name:
          id: name
          table: users
          field: name
          relationship: author
          group_type: group
          admin_label: ''
          label: Name
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          link_to_user: '1'
          overwrite_anonymous: '0'
          anonymous_text: ''
          format_username: '1'
          plugin_id: user_name
          provider: user
      filters: {  }
      sorts:
        created:
          id: created
          table: tmgmt_message
          field: created
          relationship: none
          group_type: group
          admin_label: ''
          order: DESC
          exposed: '0'
          expose:
            label: ''
          granularity: second
          plugin_id: date
          provider: views
      title: Messages
      header: {  }
      footer: {  }
      empty: {  }
      relationships:
        author:
          id: author
          table: tmgmt_message
          field: author
          relationship: none
          group_type: group
          admin_label: User
          required: '0'
          plugin_id: standard
          provider: views
        tjiid:
          id: tjiid
          table: tmgmt_message
          field: tjiid
          relationship: none
          group_type: group
          admin_label: 'Translation Job Item'
          required: '0'
          plugin_id: standard
          provider: views
      arguments:
        tjid:
          id: tjid
          table: tmgmt_message
          field: tjid
          relationship: none
          group_type: group
          admin_label: ''
          default_action: ignore
          exception:
            value: all
            title_enable: '0'
            title: All
          title_enable: '0'
          title: ''
          breadcrumb_enable: '0'
          breadcrumb: ''
          default_argument_type: fixed
          default_argument_options:
            argument: ''
          default_argument_skip_url: '0'
          summary_options:
            base_path: ''
            count: '1'
            items_per_page: '25'
            override: '0'
          summary:
            sort_order: asc
            number_of_records: '0'
            format: default_summary
          specify_validation: '0'
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          break_phrase: '0'
          not: '0'
          plugin_id: numeric
          provider: views
  block:
    display_plugin: block
    id: block
    display_title: Block
    position: '1'
    display_options:
      block_category: 'Translation Message'
    new_id: block
label: 'Translation Job messages'
module: views
id: tmgmt_ui_job_messages
tag: ''
uuid: e35624b4-cc34-4dde-80ea-df69524ab312
langcode: en
