<?php

/**
 * @file
 * Source plugin for the Translation Management system that handles entities.
 */

/**
 * Implements hook_tmgmt_source_plugin_info().
 */
function tmgmt_entity_tmgmt_source_plugin_info() {
  $info['entity'] = array(
    'label' => t('Entity'),
    'description' => t('Source handler for entities.'),
    'plugin controller class' => 'Drupal\tmgmt_entity\EntitySourcePluginController',
    'item types' => array(),
  );

  $entity_types = array_filter(variable_get('entity_translation_entity_types', array()));

  foreach ($entity_types as $entity_key) {
    $entity_info = entity_get_info($entity_key);
    $info['entity']['item types'][$entity_key] = $entity_info['label'];
  }

  return $info;
}

/**
 * Implements hook_form_ID_alter().
 *
 * Alters comment node type select box to filter out comment types that belongs
 * to non entity translatable node types.
 */
function tmgmt_entity_form_tmgmt_ui_entity_source_comment_overview_form_alter(&$form, &$form_state) {

  if (!isset($form['search_wrapper']['search']['node_type'])) {
    return;
  }

  // Change the select name to "type" as in the query submitted value will be
  // passed into node.type condition.
  $form['search_wrapper']['search']['type'] = $form['search_wrapper']['search']['node_type'];
  unset($form['search_wrapper']['search']['node_type']);

  // Set new default value.
  $form['search_wrapper']['search']['type']['#default_value'] = isset($_GET['type']) ? $_GET['type'] : NULL;

}

/**
 * Helper function to get entity translatable bundles.
 *
 * Note that for comment entity type it will return the same as for node as
 * comment bundles have no use (i.e. in queries).
 *
 * @param string $entity_type
 *   Drupal entity type.
 *
 * @return array
 *   Array of key => values, where key is type and value its label.
 */
function tmgmt_entity_get_translatable_bundles($entity_type) {

  // If given entity type does not have entity translations enabled, no reason
  // to continue.
  $enabled_types = \Drupal::service('plugin.manager.tmgmt.source')->createInstance('entity')->getItemTypes();
  if (!isset($enabled_types[$entity_type])) {
    return array();
  }

  $translatable_bundle_types = array();
  foreach (entity_get_bundles($entity_type) as $bundle_type => $bundle_definition) {
    if (content_translation_enabled($entity_type, $bundle_type)) {
      $translatable_bundle_types[$bundle_type] = $bundle_definition['label'];
    }
  }
  return $translatable_bundle_types;
}

/**
 * Gets translatable entities of a given type.
 *
 * Additionally you can specify entity property conditions, pager and limit.
 *
 * @param string $entity_type
 *   Drupal entity type.
 * @param array $property_conditions
 *   Entity properties. There is no value processing so caller must make sure
 *   the provided entity property exists for given entity type and its value
 *   is processed.
 * @param bool $pager
 *   Flag to determine if pager will be used.
 * @param int $limit
 *   Query result limit.
 *
 * @return array
 *   Array of translatable entities.
 */
function tmgmt_entity_get_translatable_entities($entity_type, $property_conditions = array(), $pager = FALSE, $limit = 20) {

  // If given entity type does not have entity translations enabled, no reason
  // to continue.
  $enabled_types = \Drupal::service('plugin.manager.tmgmt.source')->createInstance('entity')->getItemTypes();
  if (!isset($enabled_types[$entity_type])) {
    return array();
  }

  $entity_info = entity_get_info($entity_type);
  $label_key = isset($entity_info['entity_keys']['label']) ? $entity_info['entity_keys']['label'] : NULL;

  $query = db_select($entity_info['base_table'], 'e');
  $query->addField('e', $entity_info['entity_keys']['id']);

  if (!empty($label_key) && isset($property_conditions[$label_key])) {
    $search_tokens = explode(' ', $property_conditions[$label_key]);
    $or = db_or();

    foreach ($search_tokens as $search_token) {
      $search_token = trim($search_token);
      if (strlen($search_token) > 2) {
        $or->condition($label_key, "%$search_token%", 'LIKE');
      }
    }

    if ($or->count() > 0) {
      $query->condition($or);
    }

    unset($property_conditions[$label_key]);
  }

  // Add query conditions based on provided properties.
  foreach ($property_conditions as $property_name => $property_value) {
    // The comment bundle filter is handled below.
    if ($entity_type == 'comment' && $property_name == 'type') {
      continue;
    }
    $query->condition('e.' . $property_name, $property_value);
  }

  // We have to specifically handle comments and nodes.
  if (in_array($entity_type, array('comment', 'node'))) {
    $node_table_alias = 'e';

    // For comments join node table so that we can filter based on type.
    if ($entity_type == 'comment') {
      $query->join('node', 'n', 'e.nid = n.nid');
      $node_table_alias = 'n';
    }

    $bundles = array();
    foreach (array_keys(entity_get_bundles($entity_type)) as $bundle) {
      if (content_translation_enabled($entity_type, $bundle)) {
        $bundles[] = $bundle;
        break;
      }
    }
    if (!$bundles) {
      return array();
    }

    // If we have type property add condition.
    if (isset($property_conditions['type'])) {
      $query->condition($node_table_alias . '.type', $property_conditions['type']);
    }
    // If not, query db only for translatable node types.
    else {
      $query->condition($node_table_alias . '.type', $bundles);
    }
  }

  if ($pager) {
    $query = $query->extend('Drupal\Core\Database\Query\PagerSelectExtender')->limit($limit);
  }
  else {
    $query->range(0, $limit);
  }

  $query->orderBy($entity_info['entity_keys']['id'], 'DESC');

  $entity_ids = $query->execute()->fetchCol();
  $entities = array();

  if (!empty($entity_ids)) {
    $entities = entity_load_multiple($entity_type, $entity_ids);
  }

  return $entities;
}

/**
 * Implements hook_tmgmt_source_suggestions()
 */
function tmgmt_entity_tmgmt_source_suggestions(array $items, \Drupal\tmgmt\Entity\Job $job) {
  $suggestions = array();

  foreach ($items as $item) {
    if (($item instanceof \Drupal\tmgmt\Entity\JobItem) && ($item->plugin == 'entity') || ($item->plugin == 'node')) {
      // Load the entity and extract the bundle name to get all fields from the
      // current entity.
      $entity = entity_load($item->item_type, $item->item_id);

      // Loop over all fields, check if they are NOT translatable. Only if a
      // field is not translatable we may suggest a referenced entity. If so,
      // check for a supported field type (image and file currently here).
      foreach ($entity as $field) {
        $definition = $field->getFieldDefinition();

        // Loop over all field items.
        foreach ($field as $field_item) {
          // Loop over all properties of a field item.
          foreach ($field_item->getProperties(TRUE) as $property) {
            if ($property instanceof \Drupal\Core\Entity\Plugin\DataType\EntityReference && $target = $property->getTarget()) {
              $enabled = content_translation_enabled($target->entityType(), $target->bundle());
              if ($enabled) {
                // Add the translation as a suggestion.
                $suggestions[] = array(
                  'job_item' => tmgmt_job_item_create('entity', $target->entityType(), $target->id()),
                  'reason' => t('Field @label', array('@label' => $definition->getFieldLabel())),
                  'from_item' => $item->id(),
                );
              }
            }
          }
        }
      }
    }
  }

  return $suggestions;
}
